package diff

import (
	"encoding/json"
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oasdiff/oasdiff/checker"
	localizations2 "github.com/oasdiff/oasdiff/checker/localizations"
	"github.com/oasdiff/oasdiff/diff"
	"github.com/oasdiff/oasdiff/formatters"
	"github.com/oasdiff/oasdiff/load"
	"log"
	"os"
	"path/filepath"
)

var localizer = localizations2.Localizer{
	Locale:         "ja",
	FallbackLocale: "ja",
	Localizations:  localizations,
}

func GetAllDiff(path string) {
	name, err := filepath.Abs(path)
	dir, err := os.ReadDir(name)
	if err != nil {
		log.Fatalf("Error reading directory: %v", err)
	}

	for _, entry := range dir {
		rel := filepath.Join(name, entry.Name())
		GetApiDiff(rel)
	}
}

func GetApiDiff(path string) {
	dir, err := os.ReadDir(path)
	if err != nil {
		log.Fatalf("Error reading directory: %v", err)
		return
	}

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true

	versions := make(map[string]load.SpecInfo)

	for _, entry := range dir {
		if !entry.IsDir() {
			continue
		}
		version := entry.Name()
		rel := filepath.Join(path, version)
		readDir, err := os.ReadDir(rel)
		if err != nil {
			log.Fatalf("Error reading directory: %v", err)
			return
		}

		for _, dirEntry := range readDir {
			if dirEntry.Name() == "info.json" || dirEntry.Name() == "diff.json" {
				continue
			}
			specPath := filepath.Join(rel, dirEntry.Name())

			info, err := load.NewSpecInfo(loader, load.NewSource(specPath))
			if err != nil {
				log.Fatalf("Error loading spec: %v", err)
				return
			}
			versions[version] = *info
		}
	}

	for s, info := range versions {
		var jsons = make(map[string]interface{})
		for s2, specInfo := range versions {
			if s == s2 {
				continue
			}
			getDiff, err := GetDiff(&info, &specInfo)
			if err != nil {
				log.Fatalf("Error getting diff: %v", err)
			}
			var data interface{}
			err = json.Unmarshal(getDiff, &data)
			if err != nil {
				log.Fatalf("Error unmarshalling diff: %v", err)
			}
			jsons[s2] = data
		}
		marshal, err := json.Marshal(jsons)
		if err != nil {
			return
		}
		os.WriteFile(filepath.Join(path, s, "diff.json"), marshal, os.ModePerm)

	}
}

func GetDiff(spec1 *load.SpecInfo, spec2 *load.SpecInfo) ([]byte, error) {
	diffConfig := diff.NewConfig()

	diff, sourcesMap, err := diff.GetWithOperationsSourcesMap(diffConfig, spec1, spec2)
	if err != nil {
		return []byte{}, err
	}

	checkConfig := checker.NewConfig(checker.GetAllChecks())

	changes := checker.CheckBackwardCompatibilityUntilLevel(checkConfig, diff, sourcesMap, checker.INFO)

	//formatter, err := formatters.Lookup("json", formatters.FormatterOpts{})

	formatter := formatters.JSONFormatter{
		Localizer: func(key string, args ...interface{}) string {
			k := "messages." + key
			pattern := localizer.Get(k)

			if pattern == k {
				return key
			}
			fmt.Printf(pattern, args...)
			fmt.Println()
			return fmt.Sprintf(pattern, args...)
		},
	}

	changelog, err := formatter.RenderChangelog(changes, formatters.RenderOpts{}, "", "")
	if err != nil {
		return []byte{}, err
	}

	return changelog, nil
}

var localizations = map[string]string{
	"ja.messages.api-deprecated-sunset-missing":                              "非推奨APIの廃止日が設定されていません",
	"ja.messages.api-deprecated-sunset-missing-description":                  "エンドポイントが廃止日なしで非推奨になりました",
	"ja.messages.api-deprecated-sunset-parse":                                "廃止日のパースに失敗しました: %v",
	"ja.messages.api-deprecated-sunset-parse-description":                    "エンドポイントが無効な廃止日で非推奨になりました",
	"ja.messages.api-global-security-added":                                  "セキュリティスキーム %s がAPIに追加されました",
	"ja.messages.api-global-security-added-description":                      "セキュリティにセキュリティスキームが追加されました",
	"ja.messages.api-global-security-removed":                                "セキュリティスキーム %s がAPIから削除されました",
	"ja.messages.api-global-security-removed-description":                    "セキュリティからセキュリティスキームが削除されました",
	"ja.messages.api-global-security-scope-added":                            "セキュリティスコープ %s がグローバルセキュリティスキーム %s に追加されました",
	"ja.messages.api-global-security-scope-added-description":                "セキュリティのセキュリティスキームにスコープが追加されました",
	"ja.messages.api-global-security-scope-removed":                          "セキュリティスコープ %s がグローバルセキュリティスキーム %s から削除されました",
	"ja.messages.api-global-security-scope-removed-description":              "セキュリティのセキュリティスキームからスコープが削除されました",
	"ja.messages.api-invalid-stability-level":                                "安定性レベルのパースに失敗しました: %v",
	"ja.messages.api-invalid-stability-level-description":                    "無効な安定性レベルです",
	"ja.messages.api-operation-id-added":                                     "APIオペレーションID %s が追加されました",
	"ja.messages.api-operation-id-added-description":                         "エンドポイントにオペレーションIDが追加されました",
	"ja.messages.api-operation-id-removed":                                   "APIオペレーションID %s が削除され、 %s に置き換えられました",
	"ja.messages.api-operation-id-removed-description":                       "エンドポイントからオペレーションIDが削除されました",
	"ja.messages.api-path-removed-before-sunset":                             "APIパスが廃止日 %s より前に削除されました",
	"ja.messages.api-path-removed-before-sunset-description":                 "パスとエンドポイントが廃止日より前に削除されました",
	"ja.messages.api-path-removed-with-deprecation":                          "APIパスが非推奨期間を経て削除されました",
	"ja.messages.api-path-removed-without-deprecation":                       "APIパスが非推奨期間なしで削除されました",
	"ja.messages.api-path-removed-without-deprecation-description":           "パスとエンドポイントが非推奨期間なしで削除されました",
	"ja.messages.api-path-sunset-parse":                                      "廃止日のパースに失敗しました: %v",
	"ja.messages.api-path-sunset-parse-description":                          "パスとエンドポイントが無効または未設定の廃止日で削除されました",
	"ja.messages.api-removed-before-sunset":                                  "APIが廃止日 %s より前に削除されました",
	"ja.messages.api-removed-before-sunset-description":                      "エンドポイントが廃止日より前に削除されました",
	"ja.messages.api-removed-with-deprecation":                               "APIが非推奨期間を経て削除されました",
	"ja.messages.api-removed-without-deprecation":                            "APIが非推奨期間なしで削除されました",
	"ja.messages.api-removed-without-deprecation-description":                "エンドポイントが非推奨期間なしで削除されました",
	"ja.messages.api-schema-removed":                                         "スキーマ %s が削除されました",
	"ja.messages.api-schema-removed-description":                             "components/schemasからスキーマが削除されました",
	"ja.messages.api-security-added":                                         "エンドポイントのセキュリティスキーム %s がAPIに追加されました",
	"ja.messages.api-security-added-description":                             "エンドポイントにセキュリティ要件が追加されました",
	"ja.messages.api-security-component-added":                               "コンポーネントセキュリティスキーム %s が追加されました",
	"ja.messages.api-security-component-added-description":                   "components/securitySchemesにセキュリティスキームが追加されました",
	"ja.messages.api-security-component-oauth-scope-added":                   "コンポーネントセキュリティスキーム %s にOAuthスコープ %s が追加されました",
	"ja.messages.api-security-component-oauth-scope-added-description":       "components/securitySchemesのOAuthフローにスコープが追加されました",
	"ja.messages.api-security-component-oauth-scope-changed":                 "コンポーネントセキュリティスキーム %s のOAuthスコープ %s が %s から %s に更新されました",
	"ja.messages.api-security-component-oauth-scope-changed-description":     "components/securitySchemesのOAuthフローでスコープが変更されました",
	"ja.messages.api-security-component-oauth-scope-removed":                 "コンポーネントセキュリティスキーム %s のOAuthスコープ %s が削除されました",
	"ja.messages.api-security-component-oauth-scope-removed-description":     "components/securitySchemesのOAuthフローからスコープが削除されました",
	"ja.messages.api-security-component-oauth-token-url-changed":             "コンポーネントセキュリティスキーム %s のOAuthトークンURLが %s から %s に変更されました",
	"ja.messages.api-security-component-oauth-token-url-changed-description": "components/securitySchemesのOAuthフローでトークンURLが変更されました",
	"ja.messages.api-security-component-oauth-url-changed":                   "コンポーネントセキュリティスキーム %s のOAuth認証URLが %s から %s に変更されました",
	"ja.messages.api-security-component-oauth-url-changed-description":       "components/securitySchemesのOAuthフローで認証URLが変更されました",
	"ja.messages.api-security-component-removed":                             "コンポーネントセキュリティスキーム %s が削除されました",
	"ja.messages.api-security-component-removed-description":                 "components/securitySchemesからセキュリティスキームが削除されました",
	"ja.messages.api-security-component-type-changed":                        "コンポーネントセキュリティスキーム %s のタイプが %s から %s に変更されました",
	"ja.messages.api-security-component-type-changed-description":            "components/securitySchemesでセキュリティスキームのタイプが変更されました",
	"ja.messages.api-security-removed":                                       "エンドポイントのセキュリティスキーム %s がAPIから削除されました",
	"ja.messages.api-security-removed-description":                           "エンドポイントからセキュリティ要件が削除されました",
	"ja.messages.api-security-scope-added":                                   "セキュリティスコープ %s がエンドポイントのセキュリティスキーム %s に追加されました",
	"ja.messages.api-security-scope-added-description":                       "エンドポイントのセキュリティスキームにスコープが追加されました",
	"ja.messages.api-security-scope-removed":                                 "セキュリティスコープ %s がエンドポイントのセキュリティスキーム %s から削除されました",
	"ja.messages.api-security-scope-removed-description":                     "エンドポイントのセキュリティスキームからスコープが削除されました",
	"ja.messages.api-security-updated":                                       "エンドポイントのセキュリティスキーム %s が %s から %s に更新されました",
	"ja.messages.api-stability-decreased":                                    "エンドポイントの安定性レベルが %s から %s に低下しました",
	"ja.messages.api-stability-decreased-description":                        "エンドポイントの安定性レベルが低下しました",
	"ja.messages.api-sunset-date-changed-too-small":                          "APIの廃止日が %s から %s へと早まりました。新しい廃止日は %s より前には設定できず、かつ本日より少なくとも %s 日後である必要があります",
	"ja.messages.api-sunset-date-changed-too-small-description":              "変更された廃止日が、要求される最低非推奨日数を満たしていません",
	"ja.messages.api-sunset-date-too-small":                                  "廃止日 %s が近すぎます。本日より少なくとも %s 日後である必要があります",
	"ja.messages.api-sunset-date-too-small-description":                      "非推奨エンドポイントの廃止日が、要求される最低非推奨日数より前です",
	"ja.messages.api-tag-added":                                              "APIタグ %s が追加されました",
	"ja.messages.api-tag-added-description":                                  "エンドポイントにタグが追加されました",
	"ja.messages.api-tag-removed":                                            "APIタグ %s が削除されました",
	"ja.messages.api-tag-removed-description":                                "エンドポイントからタグが削除されました",
	"ja.messages.at":                                                                  "場所",
	"ja.messages.endpoint-added":                                                      "エンドポイントが追加されました",
	"ja.messages.endpoint-added-description":                                          "エンドポイント追加",
	"ja.messages.endpoint-deprecated":                                                 "エンドポイントが非推奨になりました",
	"ja.messages.endpoint-deprecated-description":                                     "エンドポイント非推奨",
	"ja.messages.endpoint-reactivated":                                                "エンドポイントが再有効化されました",
	"ja.messages.endpoint-reactivated-description":                                    "エンドポイントが再有効化されました (deprecationがfalseに設定)",
	"ja.messages.in":                                                                  "内",
	"ja.messages.new-optional-request-default-parameter-to-existing-path":             "新しいオプションの %s リクエストパラメータ %s がすべてのパスオペレーションに追加されました",
	"ja.messages.new-optional-request-default-parameter-to-existing-path-description": "オプションのリクエストパラメータがパスレベルで追加されました",
	"ja.messages.new-optional-request-parameter":                                      "新しいオプションの %s リクエストパラメータ %s が追加されました",
	"ja.messages.new-optional-request-parameter-description":                          "オプションのリクエストパラメータがエンドポイントに追加されました",
	"ja.messages.new-optional-request-property":                                       "新しいオプションのリクエストプロパティ %s が追加されました",
	"ja.messages.new-optional-request-property-description":                           "オプションのプロパティがリクエストに追加されました",
	"ja.messages.new-request-path-parameter":                                          "新しいパスリクエストパラメータ %s が追加されました",
	"ja.messages.new-request-path-parameter-description":                              "新しいリクエストパスパラメータ",
	"ja.messages.new-required-request-default-parameter-to-existing-path":             "新しい必須の %s リクエストパラメータ %s がすべてのパスオペレーションに追加されました",
	"ja.messages.new-required-request-default-parameter-to-existing-path-description": "必須のリクエストパラメータがパスレベルで追加されました",
	"ja.messages.new-required-request-header-property":                                "新しい必須の %s リクエストヘッダープロパティ %s が追加されました",
	"ja.messages.new-required-request-header-property-description":                    "新しい必須のリクエストヘッダー",
	"ja.messages.new-required-request-parameter":                                      "新しい必須の %s リクエストパラメータ %s が追加されました",
	"ja.messages.new-required-request-parameter-description":                          "必須のリクエストパラメータがエンドポイントに追加されました",
	"ja.messages.new-required-request-property":                                       "新しい必須のリクエストプロパティ %s が追加されました",
	"ja.messages.new-required-request-property-description":                           "必須のプロパティがリクエストに追加されました",
	"ja.messages.new-required-request-property-with-default":                          "デフォルト値を持つ新しい必須のリクエストプロパティ %s が追加されました",
	"ja.messages.new-required-request-property-with-default-description":              "デフォルト値を持つ必須のプロパティがリクエストに追加されました",
	"ja.messages.optional-response-header-removed":                                    "オプションのレスポンスヘッダー %s がステータス %s から削除されました",
	"ja.messages.optional-response-header-removed-description":                        "オプションのレスポンスヘッダーが削除されました",
	"ja.messages.pattern-changed-warn-comment":                                        "これは警告です。新しいパターンが以前のパターンのスーパーセット（上位互換）であるか（例: '[0-9]+' から '[0-9]*' への変更）を自動的に分析することが困難なためです。",
	"ja.messages.request-body-added-optional":                                         "オプションのリクエストボディが追加されました",
	"ja.messages.request-body-added-optional-description":                             "オプションのリクエストボディ追加",
	"ja.messages.request-body-added-required":                                         "必須のリクエストボディが追加されました",
	"ja.messages.request-body-added-required-description":                             "必須のリクエストボディ追加",
	"ja.messages.request-body-all-of-added":                                           "リクエストボディの 'allOf' リストに %s が追加されました",
	"ja.messages.request-body-all-of-added-description":                               "リクエストボディのallOfにサブスキーマが追加されました",
	"ja.messages.request-body-all-of-removed":                                         "リクエストボディの 'allOf' リストから %s が削除されました",
	"ja.messages.request-body-all-of-removed-description":                             "リクエストボディのallOfからサブスキーマが削除されました",
	"ja.messages.request-body-any-of-added":                                           "リクエストボディの 'anyOf' リストに %s が追加されました",
	"ja.messages.request-body-any-of-added-description":                               "リクエストボディのanyOfにサブスキーマが追加されました",
	"ja.messages.request-body-any-of-removed":                                         "リクエストボディの 'anyOf' リストから %s が削除されました",
	"ja.messages.request-body-any-of-removed-description":                             "リクエストボディのanyOfからサブスキーマが削除されました",
	"ja.messages.request-body-became-enum":                                            "リクエストボディがenum値のリストに制限されました",
	"ja.messages.request-body-became-enum-description":                                "リクエストボディがenumに制限されました",
	"ja.messages.request-body-became-not-nullable":                                    "リクエストボディがnull非許容になりました",
	"ja.messages.request-body-became-not-nullable-description":                        "リクエストボディの有効な値からnullが除外されました",
	"ja.messages.request-body-became-nullable":                                        "リクエストボディがnull許容になりました",
	"ja.messages.request-body-became-nullable-description":                            "リクエストボディの有効な値にnullが追加されました",
	"ja.messages.request-body-became-optional":                                        "リクエストボディがオプションになりました",
	"ja.messages.request-body-became-optional-description":                            "リクエストボディがオプションに変更",
	"ja.messages.request-body-became-required":                                        "リクエストボディが必須になりました",
	"ja.messages.request-body-became-required-description":                            "リクエストボディが必須に変更",
	"ja.messages.request-body-default-value-added":                                    "リクエストボディ %s にデフォルト値 %s が追加されました",
	"ja.messages.request-body-default-value-added-description":                        "リクエストボディのデフォルト値が設定されました",
	"ja.messages.request-body-default-value-changed":                                  "リクエストボディ %s のデフォルト値が %s から %s に変更されました",
	"ja.messages.request-body-default-value-changed-description":                      "リクエストボディのデフォルト値が変更されました",
	"ja.messages.request-body-default-value-removed":                                  "リクエストボディ %s のデフォルト値 %s が削除されました",
	"ja.messages.request-body-default-value-removed-description":                      "リクエストボディのデフォルト値が解除されました",
	"ja.messages.request-body-discriminator-added":                                    "リクエストdiscriminatorが追加されました",
	"ja.messages.request-body-discriminator-added-description":                        "リクエストボディにdiscriminatorが追加されました",
	"ja.messages.request-body-discriminator-mapping-added":                            "リクエストdiscriminatorにマッピングキー %s が追加されました",
	"ja.messages.request-body-discriminator-mapping-added-description":                "リクエストボディにdiscriminatorマッピングが追加されました",
	"ja.messages.request-body-discriminator-mapping-changed":                          "リクエストdiscriminatorのキー %s にマップされた値が %s から %s に変更されました",
	"ja.messages.request-body-discriminator-mapping-changed-description":              "リクエストボディのdiscriminatorマッピングが変更されました",
	"ja.messages.request-body-discriminator-mapping-deleted":                          "リクエストdiscriminatorからマッピングキー %s が削除されました",
	"ja.messages.request-body-discriminator-mapping-deleted-description":              "リクエストボディのdiscriminatorマッピングが削除されました",
	"ja.messages.request-body-discriminator-property-name-changed":                    "リクエストdiscriminatorのプロパティ名が %s から %s に変更されました",
	"ja.messages.request-body-discriminator-property-name-changed-description":        "リクエストボディのdiscriminatorプロパティ名が変更されました",
	"ja.messages.request-body-discriminator-removed":                                  "リクエストdiscriminatorが削除されました",
	"ja.messages.request-body-discriminator-removed-description":                      "リクエストボディのdiscriminatorが削除されました",
	"ja.messages.request-body-enum-value-removed":                                     "リクエストボディのenum値 %s が削除されました",
	"ja.messages.request-body-enum-value-removed-description":                         "リクエストボディのenum値が削除されました",
	"ja.messages.request-body-max-decreased":                                          "リクエストボディのmaxが %s に減少しました",
	"ja.messages.request-body-max-decreased-description":                              "リクエストボディのmaxが減少",
	"ja.messages.request-body-max-increased":                                          "リクエストボディのmaxが %s から %s に増加しました",
	"ja.messages.request-body-max-increased-description":                              "リクエストボディのmaxが増加",
	"ja.messages.request-body-max-length-decreased":                                   "リクエストボディのmaxLengthが %s に減少しました",
	"ja.messages.request-body-max-length-decreased-description":                       "リクエストボディのmaxLengthが減少",
	"ja.messages.request-body-max-length-increased":                                   "リクエストボディのmaxLengthが %s から %s に増加しました",
	"ja.messages.request-body-max-length-increased-description":                       "リクエストボディのmaxLengthが増加",
	"ja.messages.request-body-max-length-set":                                         "リクエストボディのmaxLengthが %s に設定されました",
	"ja.messages.request-body-max-length-set-comment":                                 "これは警告です。この設定が必要な場合がありますが、仕様を変更する前に、クライアントがこの制約をサポートしているか確認すべきです。",
	"ja.messages.request-body-max-length-set-description":                             "リクエストボディのmaxLengthが設定されました",
	"ja.messages.request-body-max-set":                                                "リクエストボディのmaxが %s に設定されました",
	"ja.messages.request-body-max-set-comment":                                        "これは警告です。この設定が必要な場合がありますが、仕様を変更する前に、クライアントがこの制約をサポートしているか確認すべきです。",
	"ja.messages.request-body-max-set-description":                                    "リクエストボディのmaxが設定されました",
	"ja.messages.request-body-media-type-added":                                       "メディアタイプ %s がリクエストボディに追加されました",
	"ja.messages.request-body-media-type-added-description":                           "リクエストボディのメディアタイプが追加されました",
	"ja.messages.request-body-media-type-removed":                                     "メディアタイプ %s がリクエストボディから削除されました",
	"ja.messages.request-body-media-type-removed-description":                         "リクエストボディのメディアタイプが削除されました",
	"ja.messages.request-body-min-decreased":                                          "リクエストボディのminが %s から %s に減少しました",
	"ja.messages.request-body-min-decreased-description":                              "リクエストボディのminが減少",
	"ja.messages.request-body-min-increased":                                          "リクエストボディのminが %s に増加しました",
	"ja.messages.request-body-min-increased-description":                              "リクエストボディのminが増加",
	"ja.messages.request-body-min-items increased-description":                        "リクエストボディのminItemsが増加",
	"ja.messages.request-body-min-items set-description":                              "リクエストボディのminItemsが設定されました",
	"ja.messages.request-body-min-items-decreased":                                    "リクエストボディのminItemsが %s から %s に減少しました",
	"ja.messages.request-body-min-items-increased":                                    "リクエストボディのminItemsが %s に増加しました",
	"ja.messages.request-body-min-items-set":                                          "リクエストボディのminItemsが %s に設定されました",
	"ja.messages.request-body-min-items-set-comment":                                  "これは警告です。この設定が必要な場合がありますが、仕様を変更する前に、クライアントがこの制約をサポートしているか確認すべきです。",
	"ja.messages.request-body-min-length-decreased":                                   "リクエストボディのminLengthが %s から %s に減少しました",
	"ja.messages.request-body-min-length-decreased-description":                       "リクエストボディのminLengthが減少",
	"ja.messages.request-body-min-length-increased":                                   "リクエストボディのminLengthが %s から %s に増加しました",
	"ja.messages.request-body-min-length-increased-description":                       "リクエストボディのminLengthが増加",
	"ja.messages.request-body-min-set":                                                "リクエストボディのminが %s に設定されました",
	"ja.messages.request-body-min-set-comment":                                        "これは警告です。この設定が必要な場合がありますが、仕様を変更する前に、クライアントがこの制約をサポートしているか確認すべきです。",
	"ja.messages.request-body-min-set-description":                                    "リクエストボディのminが設定されました",
	"ja.messages.request-body-one-of-added":                                           "リクエストボディの 'oneOf' リストに %s が追加されました",
	"ja.messages.request-body-one-of-added-description":                               "リクエストボディのoneOfにサブスキーマが追加されました",
	"ja.messages.request-body-one-of-removed":                                         "リクエストボディの 'oneOf' リストから %s が削除されました",
	"ja.messages.request-body-one-of-removed-description":                             "リクエストボディのoneOfからサブスキーマが削除されました",
	"ja.messages.request-body-removed":                                                "リクエストボディが削除されました",
	"ja.messages.request-body-removed-description":                                    "リクエストボディ削除",
	"ja.messages.request-body-type-changed":                                           "リクエストボディのtype/formatが %s/%s から %s/%s に変更されました",
	"ja.messages.request-body-type-changed-description":                               "リクエストボディのタイプが変更されました",
	"ja.messages.request-body-type-generalized":                                       "リクエストボディのtype/formatが %s/%s から %s/%s に汎化されました",
	"ja.messages.request-body-type-generalized-description":                           "リクエストボディのタイプが汎化されました",
	"ja.messages.request-header-property-became-enum":                                 "%s リクエストヘッダーのプロパティ %s がenum値のリストに制限されました",
	"ja.messages.request-header-property-became-enum-description":                     "リクエストヘッダーのプロパティがenumに制限されました",
	"ja.messages.request-header-property-became-required":                             "%s リクエストヘッダーのプロパティ %s が必須になりました",
	"ja.messages.request-header-property-became-required-description":                 "リクエストヘッダーのプロパティが必須になりました",
	"ja.messages.request-optional-property-became-not-read-only":                      "オプションのリクエストプロパティ %s が読み取り専用でなくなりました",
	"ja.messages.request-optional-property-became-not-read-only-description":          "オプションのリクエストプロパティが読み取り専用でなくなりました",
	"ja.messages.request-optional-property-became-not-write-only":                     "オプションのリクエストプロパティ %s が書き込み専用でなくなりました",
	"ja.messages.request-optional-property-became-not-write-only-description":         "オプションのリクエストプロパティが書き込み専用でなくなりました",
	"ja.messages.request-optional-property-became-read-only":                          "オプションのリクエストプロパティ %s が読み取り専用になりました",
	"ja.messages.request-optional-property-became-read-only-description":              "オプションのリクエストプロパティが読み取り専用になりました",
	"ja.messages.request-optional-property-became-write-only":                         "オプションのリクエストプロパティ %s が書き込み専用になりました",
	"ja.messages.request-optional-property-became-write-only-description":             "オプションのリクエストプロパティが書き込み専用になりました",
	"ja.messages.request-parameter-became-enum":                                       "%s リクエストパラメータ %s がenum値のリストに制限されました",
	"ja.messages.request-parameter-became-enum-description":                           "リクエストパラメータがenumに制限されました",
	"ja.messages.request-parameter-became-optional":                                   "%s リクエストパラメータ %s がオプションになりました",
	"ja.messages.request-parameter-became-optional-description":                       "リクエストパラメータがオプションになりました",
	"ja.messages.request-parameter-became-required":                                   "%s リクエストパラメータ %s が必須になりました",
	"ja.messages.request-parameter-became-required-description":                       "リクエストパラメータが必須になりました",
	"ja.messages.request-parameter-default-value-added":                               "%s リクエストパラメータ %s にデフォルト値 %s が追加されました",
	"ja.messages.request-parameter-default-value-added-description":                   "リクエストパラメータのデフォルト値が設定されました",
	"ja.messages.request-parameter-default-value-changed":                             "%s リクエストパラメータ %s のデフォルト値が %s から %s に変更されました",
	"ja.messages.request-parameter-default-value-changed-description":                 "リクエストパラメータのデフォルト値が変更されました",
	"ja.messages.request-parameter-default-value-removed":                             "%s リクエストパラメータ %s のデフォルト値 %s が削除されました",
	"ja.messages.request-parameter-default-value-removed-description":                 "リクエストパラメータのデフォルト値が解除されました",
	"ja.messages.request-parameter-deprecated":                                        "%s リクエストパラメータ %s が非推奨になりました",
	"ja.messages.request-parameter-deprecated-sunset-missing":                         "%s リクエストパラメータ %s が廃止日なしで非推奨になりました",
	"ja.messages.request-parameter-enum-value-added":                                  "新しいenum値 %s が %s リクエストパラメータ %s に追加されました",
	"ja.messages.request-parameter-enum-value-added-description":                      "リクエストパラメータにenum値が追加されました",
	"ja.messages.request-parameter-enum-value-removed":                                "enum値 %s が %s リクエストパラメータ %s から削除されました",
	"ja.messages.request-parameter-enum-value-removed-description":                    "リクエストパラメータからenum値が削除されました",
	"ja.messages.request-parameter-max-decreased":                                     "%s リクエストパラメータ %s のmaxが %s から %s に減少しました",
	"ja.messages.request-parameter-max-decreased-description":                         "リクエストパラメータのmaxが減少しました",
	"ja.messages.request-parameter-max-increased":                                     "%s リクエストパラメータ %s のmaxが %s から %s に増加しました",
	"ja.messages.request-parameter-max-increased-description":                         "リクエストパラメータのmaxが増加しました",
	"ja.messages.request-parameter-max-items-decreased":                               "%s リクエストパラメータ %s のmaxItemsが %s から %s に減少しました",
	"ja.messages.request-parameter-max-items-decreased-description":                   "リクエストパラメータのmaxItemsが減少しました",
	"ja.messages.request-parameter-max-items-increased":                               "%s リクエストパラメータ %s のmaxItemsが %s から %s に増加しました",
	"ja.messages.request-parameter-max-items-increased-description":                   "リクエストパラメータのmaxItemsが増加しました",
	"ja.messages.request-parameter-max-length-decreased":                              "%s リクエストパラメータ %s のmaxLengthが %s から %s に減少しました",
	"ja.messages.request-parameter-max-length-decreased-description":                  "リクエストパラメータのmaxLengthが減少しました",
	"ja.messages.request-parameter-max-length-increased":                              "%s リクエストパラメータ %s のmaxLengthが %s から %s に増加しました",
	"ja.messages.request-parameter-max-length-increased-description":                  "リクエストパラメータのmaxLengthが増加しました",
	"ja.messages.request-parameter-max-length-set":                                    "%s リクエストパラメータ %s のmaxLengthが %s に設定されました",
	"ja.messages.request-parameter-max-length-set-comment":                            "これは警告です。セキュリティ上の理由や現在の仕様のエラーにより設定が必要な場合があります。しかし、仕様を変更する前に、クライアントがこの制約をサポートしているか確認すべきです。",
	"ja.messages.request-parameter-max-length-set-description":                        "リクエストパラメータのmaxLengthが設定されました",
	"ja.messages.request-parameter-max-set":                                           "%s リクエストパラメータ %s のmaxが %s に設定されました",
	"ja.messages.request-parameter-max-set-comment":                                   "これは警告です。セキュリティ上の理由や現在の仕様のエラーにより設定が必要な場合があります。しかし、仕様を変更する前に、クライアントがこの制약をサポートしているか確認すべきです。",
	"ja.messages.request-parameter-max-set-description":                               "リクエストパラメータのmaxが設定されました",
	"ja.messages.request-parameter-min-decreased":                                     "%s リクエストパラメータ %s のminが %s から %s に減少しました",
	"ja.messages.request-parameter-min-decreased-description":                         "リクエストパラメータのminが減少しました",
	"ja.messages.request-parameter-min-increased":                                     "%s リクエストパラメータ %s のminが %s から %s に増加しました",
	"ja.messages.request-parameter-min-increased-description":                         "リクエストパラメータのminが増加しました",
	"ja.messages.request-parameter-min-items-decreased":                               "%s リクエストパラメータ %s のminItemsが %s から %s に減少しました",
	"ja.messages.request-parameter-min-items-decreased-description":                   "リクエストパラメータのminItemsが減少しました",
	"ja.messages.request-parameter-min-items-increased":                               "%s リクエストパラメータ %s のminItemsが %s から %s に増加しました",
	"ja.messages.request-parameter-min-items-increased-description":                   "リクエストパラメータのminItemsが増加しました",
	"ja.messages.request-parameter-min-items-set":                                     "%s リクエストパラメータ %s のminItemsが %s に設定されました",
	"ja.messages.request-parameter-min-items-set-comment":                             "これは警告です。セキュリティ上の理由や現在の仕様のエラーにより設定が必要な場合があります。しかし、仕様を変更する前に、クライアントがこの制約をサポートしているか確認すべきです。",
	"ja.messages.request-parameter-min-items-set-description":                         "リクエストパラメータのminItemsが設定されました",
	"ja.messages.request-parameter-min-length-decreased":                              "%s リクエストパラメータ %s のminLengthが %s から %s に減少しました",
	"ja.messages.request-parameter-min-length-decreased-description":                  "リクエストパラメータのminLengthが減少しました",
	"ja.messages.request-parameter-min-length-increased":                              "%s リクエストパラメータ %s のminLengthが %s から %s に増加しました",
	"ja.messages.request-parameter-min-length-increased-description":                  "リクエストパラメータのminLengthが増加しました",
	"ja.messages.request-parameter-min-set":                                           "%s リクエストパラメータ %s のminが %s に設定されました",
	"ja.messages.request-parameter-min-set-comment":                                   "これは警告です。セキュリティ上の理由や現在の仕様のエラーにより設定が必要な場合があります。しかし、仕様を変更する前に、クライアントがこの制約をサポートしているか確認すべきです。",
	"ja.messages.request-parameter-min-set-description":                               "リクエストパラメータのminが設定されました",
	"ja.messages.request-parameter-pattern-added":                                     "パターン %s が %s リクエストパラメータ %s に追加されました",
	"ja.messages.request-parameter-pattern-added-description":                         "リクエストパラメータのパターンが設定されました",
	"ja.messages.request-parameter-pattern-changed":                                   "%s リクエストパラメータ %s のパターンが %s から %s に変更されました",
	"ja.messages.request-parameter-pattern-changed-description":                       "リクエストパラメータのパターンが変更されました",
	"ja.messages.request-parameter-pattern-generalized":                               "%s リクエストパラメータ %s のパターンが %s からより汎用的なパターン %s に変更されました",
	"ja.messages.request-parameter-pattern-generalized-description":                   "リクエストパラメータのパターンが汎化されました",
	"ja.messages.request-parameter-pattern-removed":                                   "パターン %s が %s リクエストパラメータ %s から削除されました",
	"ja.messages.request-parameter-pattern-removed-description":                       "リクエストパラメータのパターンが解除されました",
	"ja.messages.request-parameter-property-type-changed":                             "%s リクエストパラメータ %s のプロパティ %s のtype/formatが %s/%s から %s/%s に変更されました",
	"ja.messages.request-parameter-property-type-changed-description":                 "リクエストパラメータのプロパティタイプが変更されました",
	"ja.messages.request-parameter-property-type-changed-warn-comment":                "これは警告です。パラメータオブジェクトは様々な方法で渡される可能性があり、このタイプの変更を許容する場合としない場合があるためです。",
	"ja.messages.request-parameter-property-type-generalized":                         "%s リクエストパラメータ %s のプロパティ %s のtype/formatが %s/%s から %s/%s に汎化されました",
	"ja.messages.request-parameter-property-type-generalized-description":             "リクエストパラメータのプロパティタイプが汎化されました",
	"ja.messages.request-parameter-property-type-specialized":                         "%s リクエストパラメータ %s のプロパティ %s のtype/formatが %s/%s から %s/%s に特殊化されました",
	"ja.messages.request-parameter-property-type-specialized-description":             "リクエストパラメータのプロパティタイプが特殊化されました",
	"ja.messages.request-parameter-reactivated":                                       "%s リクエストパラメータ %s が再有効化されました",
	"ja.messages.request-parameter-removed":                                           "%s リクエストパラメータ %s が削除されました",
	"ja.messages.request-parameter-removed-before-sunset":                             "%s リクエストパラメータ %s が廃止日 %s より前に削除されました",
	"ja.messages.request-parameter-removed-comment":                                   "これは警告です。一部のアプリは予期しないパラメータを受け取るとエラーを返すことがあります。最初にパラメータを非推奨にすることを推奨します。",
	"ja.messages.request-parameter-removed-description":                               "リクエストパラメータが削除されました",
	"ja.messages.request-parameter-removed-with-deprecation":                          "%s リクエストパラメータ %s が非推奨期間を経て削除されました",
	"ja.messages.request-parameter-sunset-date-changed-too-small":                     "%s リクエストパラメータ %s の廃止日が %s から %s へと早まりました。新しい廃止日は %s より前には設定できず、かつ本日より少なくとも %s 日後である必要があります",
	"ja.messages.request-parameter-sunset-date-too-small":                             "%s リクエストパラメータ %s の廃止日 %s が近すぎます。本日より少なくとも %s 日後である必要があります",
	"ja.messages.request-parameter-sunset-deleted":                                    "%s リクエストパラメータ %s の廃止日が削除されましたが、deprecated=trueは維持されます",
	"ja.messages.request-parameter-sunset-parse":                                      "%s リクエストパラメータ %s の廃止日のパースに失敗しました: %v",
	"ja.messages.request-parameter-type-changed":                                      "%s リクエストパラメータ %s のtype/formatが %s/%s から %s/%s に変更されました",
	"ja.messages.request-parameter-type-changed-description":                          "リクエストパラメータのタイプが変更されました",
	"ja.messages.request-parameter-type-generalized":                                  "%s リクエストパラメータ %s のtype/formatが %s/%s から %s/%s に汎化されました",
	"ja.messages.request-parameter-type-generalized-description":                      "リクエストパラメータのタイプが汎化されました",
	"ja.messages.request-parameter-x-extensible-enum-value-removed":                   "x-extensible-enum値 %s が %s リクエストパラメータ %s から削除されました",
	"ja.messages.request-parameter-x-extensible-enum-value-removed-description":       "リクエストパラメータのx-extensible-enum値が削除されました",
	"ja.messages.request-property-all-of-added":                                       "%s リクエストプロパティの 'allOf' リストに %s が追加されました",
	"ja.messages.request-property-all-of-added-description":                           "リクエストプロパティのallOfにサブスキーマが追加されました",
	"ja.messages.request-property-all-of-removed":                                     "%s リクエストプロパティの 'allOf' リストから %s が削除されました",
	"ja.messages.request-property-all-of-removed-description":                         "リクエストプロパティのallOfからサブスキーマが削除されました",
	"ja.messages.request-property-any-of-added":                                       "%s リクエストプロパティの 'anyOf' リストに %s が追加されました",
	"ja.messages.request-property-any-of-added-description":                           "リクエストプロパティのanyOfからサブスキーマが削除されました",
	"ja.messages.request-property-any-of-removed":                                     "%s リクエストプロパティの 'anyOf' リストから %s が削除されました",
	"ja.messages.request-property-any-of-removed-description":                         "リクエストプロパティのanyOfからサブスキーマが削除されました",
	"ja.messages.request-property-became-enum":                                        "リクエストプロパティ %s がenum値のリストに制限されました",
	"ja.messages.request-property-became-enum-description":                            "リクエストプロパティがenumに制限されました",
	"ja.messages.request-property-became-not-nullable":                                "リクエストプロパティ %s がnull非許容になりました",
	"ja.messages.request-property-became-not-nullable-description":                    "リクエストプロパティがnull非許容になりました",
	"ja.messages.request-property-became-nullable":                                    "リクエストプロパティ %s がnull許容になりました",
	"ja.messages.request-property-became-nullable-description":                        "リクエストプロパティがnull許容になりました",
	"ja.messages.request-property-became-optional":                                    "リクエストプロパティ %s がオプションになりました",
	"ja.messages.request-property-became-optional-description":                        "リクエストプロパティがオプションになりました",
	"ja.messages.request-property-became-required":                                    "リクエストプロパティ %s が必須になりました",
	"ja.messages.request-property-became-required-description":                        "リクエストプロパティが必須になりました",
	"ja.messages.request-property-became-required-with-default":                       "デフォルト値を持つリクエストプロパティ %s が必須になりました",
	"ja.messages.request-property-became-required-with-default-description":           "デフォルト値を持つリクエストプロパティが必須になりました",
	"ja.messages.request-property-default-value-added":                                "%s リクエストプロパティにデフォルト値 %s が追加されました",
	"ja.messages.request-property-default-value-added-description":                    "リクエストプロパティのデフォルト値が設定されました",
	"ja.messages.request-property-default-value-changed":                              "%s リクエストプロパティのデフォルト値が %s から %s に変更されました",
	"ja.messages.request-property-default-value-changed-description":                  "リクエストプロパティのデフォルト値が変更されました",
	"ja.messages.request-property-default-value-removed":                              "%s リクエストプロパティのデフォルト値 %s が削除されました",
	"ja.messages.request-property-default-value-removed-description":                  "リクエストプロパティのデフォルト値が解除されました",
	"ja.messages.request-property-discriminator-added":                                "%s リクエストプロパティにdiscriminatorが追加されました",
	"ja.messages.request-property-discriminator-added-description":                    "リクエストプロパティにdiscriminatorが追加されました",
	"ja.messages.request-property-discriminator-mapping-added":                        "%s リクエストプロパティにdiscriminatorマッピングキー %s が追加されました",
	"ja.messages.request-property-discriminator-mapping-added-description":            "リクエストプロパティにdiscriminatorマッピングが追加されました",
	"ja.messages.request-property-discriminator-mapping-changed":                      "%s リクエストプロパティのdiscriminatorキー %s にマップされた値が %s から %s に変更されました",
	"ja.messages.request-property-discriminator-mapping-changed-description":          "リクエストプロパティのdiscriminatorマッピングが変更されました",
	"ja.messages.request-property-discriminator-mapping-deleted":                      "%s リクエストプロパティからdiscriminatorマッピングキー %s が削除されました",
	"ja.messages.request-property-discriminator-mapping-deleted-description":          "リクエストプロパティのdiscriminatorマッピングが削除されました",
	"ja.messages.request-property-discriminator-property-name-changed":                "%s リクエストプロパティのdiscriminatorプロパティ名が %s から %s に変更されました",
	"ja.messages.request-property-discriminator-property-name-changed-description":    "リクエストプロパティのdiscriminatorプロパティ名が変更されました",
	"ja.messages.request-property-discriminator-removed":                              "%s リクエストプロパティからdiscriminatorが削除されました",
	"ja.messages.request-property-discriminator-removed-description":                  "リクエストプロパティのdiscriminatorが削除されました",
	"ja.messages.request-property-enum-value-added":                                   "新しいenum値 %s がリクエストプロパティ %s に追加されました",
	"ja.messages.request-property-enum-value-added-description":                       "リクエストプロパティにenum値が追加されました",
	"ja.messages.request-property-enum-value-removed":                                 "リクエストプロパティ %s のenum値 %s が削除されました",
	"ja.messages.request-property-enum-value-removed-description":                     "リクエストプロパティのenum値が削除されました",
	"ja.messages.request-property-max-decreased":                                      "%s リクエストプロパティのmaxが %s に減少しました",
	"ja.messages.request-property-max-decreased-description":                          "リクエストプロパティのmaxが減少しました",
	"ja.messages.request-property-max-increased":                                      "%s リクエストプロパティのmaxが %s から %s に増加しました",
	"ja.messages.request-property-max-increased-description":                          "リクエストプロパティのmaxが増加しました",
	"ja.messages.request-property-max-length-decreased":                               "%s リクエストプロパティのmaxLengthが %s に減少しました",
	"ja.messages.request-property-max-length-decreased-description":                   "リクエストプロパティのmaxLengthが減少しました",
	"ja.messages.request-property-max-length-increased":                               "%s リクエストプロパティのmaxLengthが %s から %s に増加しました",
	"ja.messages.request-property-max-length-increased-description":                   "リクエストプロパティのmaxLengthが増加しました",
	"ja.messages.request-property-max-length-set":                                     "%s リクエストプロパティのmaxLengthが %s に設定されました",
	"ja.messages.request-property-max-length-set-comment":                             "これは警告です。この設定が必要な場合がありますが、仕様を変更する前に、クライアントがこの制約をサポートしているか確認すべきです。",
	"ja.messages.request-property-max-length-set-description":                         "リクエストプロパティのmaxLengthが設定されました",
	"ja.messages.request-property-max-set":                                            "%s リクエストプロパティのmaxが %s に設定されました",
	"ja.messages.request-property-max-set-comment":                                    "これは警告です。この設定が必要な場合がありますが、仕様を変更する前に、クライアントがこの制約をサポートしているか確認すべきです。",
	"ja.messages.request-property-max-set-description":                                "リクエストプロパティのmaxが設定されました",
	"ja.messages.request-property-min-decreased":                                      "%s リクエストプロパティのminが %s から %s に減少しました",
	"ja.messages.request-property-min-decreased-description":                          "リクエストプロパティのminが減少しました",
	"ja.messages.request-property-min-increased":                                      "%s リクエストプロパティのminが %s に増加しました",
	"ja.messages.request-property-min-increased-description":                          "リクエストプロパティのminが増加しました",
	"ja.messages.request-property-min-items-decreased":                                "%s リクエストプロパティのminItemsが %s から %s に減少しました",
	"ja.messages.request-property-min-items-increased":                                "%s リクエストプロパティのminItemsが %s に増加しました",
	"ja.messages.request-property-min-items-increased-description":                    "リクエストプロパティのminItemsが増加しました",
	"ja.messages.request-property-min-items-set":                                      "%s リクエストプロパティのminItemsが %s に設定されました",
	"ja.messages.request-property-min-items-set-comment":                              "これは警告です。この設定が必要な場合がありますが、仕様を変更する前に、クライアントがこの制約をサポートしているか確認すべきです。",
	"ja.messages.request-property-min-items-set-description":                          "リクエストプロパティのminItemsが設定されました",
	"ja.messages.request-property-min-length-decreased":                               "%s リクエストプロパティのminLengthが %s から %s に減少しました",
	"ja.messages.request-property-min-length-decreased-description":                   "リクエストプロパティのminLengthが減少しました",
	"ja.messages.request-property-min-length-increased":                               "%s リクエストプロパティのminLengthが %s から %s に増加しました",
	"ja.messages.request-property-min-length-increased-description":                   "リクエストプロパティのminLengthが増加しました",
	"ja.messages.request-property-min-set":                                            "%s リクエストプロパティのminが %s に設定されました",
	"ja.messages.request-property-min-set-comment":                                    "これは警告です。この設定が必要な場合がありますが、仕様を変更する前に、クライアントがこの制約をサポートしているか確認すべきです。",
	"ja.messages.request-property-min-set-description":                                "リクエストプロパティのminが設定されました",
	"ja.messages.request-property-one-of-added":                                       "%s リクエストプロパティの 'oneOf' リストに %s が追加されました",
	"ja.messages.request-property-one-of-added-description":                           "リクエストプロパティのoneOfにサブスキーマが追加されました",
	"ja.messages.request-property-one-of-removed":                                     "%s リクエストプロパティの 'oneOf' リストから %s が削除されました",
	"ja.messages.request-property-one-of-removed-description":                         "リクエストプロパティのoneOfからサブスキーマが削除されました",
	"ja.messages.request-property-pattern-added":                                      "パターン %s がリクエストプロパティ %s に追加されました",
	"ja.messages.request-property-pattern-added-description":                          "リクエストプロパティのパターンが設定されました",
	"ja.messages.request-property-pattern-changed":                                    "リクエストプロパティ %s のパターンが %s から %s に変更されました",
	"ja.messages.request-property-pattern-changed-description":                        "リクエストプロパティのパターンが変更されました",
	"ja.messages.request-property-pattern-generalized":                                "リクエストプロパティ %s のパターンが %s からより汎用的なパターン %s に変更されました",
	"ja.messages.request-property-pattern-generalized-description":                    "リクエストプロパティのパターンが汎化されました",
	"ja.messages.request-property-pattern-removed":                                    "パターン %s がリクエストプロパティ %s から削除されました",
	"ja.messages.request-property-pattern-removed-description":                        "リクエストプロパティのパターンが解除されました",
	"ja.messages.request-property-removed":                                            "リクエストプロパティ %s が削除されました",
	"ja.messages.request-property-removed-description":                                "リクエストプロパティが削除されました",
	"ja.messages.request-property-type-changed":                                       "%s リクエストプロパティのtype/formatが %s/%s から %s/%s に変更されました",
	"ja.messages.request-property-type-changed-description":                           "リクエストプロパティのタイプが変更されました",
	"ja.messages.request-property-type-generalized":                                   "%s リクエストプロパティのtype/formatが %s/%s から %s/%s に汎化されました",
	"ja.messages.request-property-type-generalized-description":                       "リクエストプロパティのタイプが汎化されました",
	"ja.messages.request-property-x-extensible-enum-value-removed":                    "リクエストプロパティ %s のx-extensible-enum値 %s が削除されました",
	"ja.messages.request-property-x-extensible-enum-value-removed-description":        "リクエストプロパティのx-extensible-enum値が削除されました",
	"ja.messages.request-read-only-property-enum-value-removed":                       "読み取り専用リクエストプロパティ %s のenum値 %s が削除されました",
	"ja.messages.request-read-only-property-enum-value-removed-description":           "読み取り専用リクエストプロパティのenum値が削除されました",
	"ja.messages.request-read-only-property-max-decreased":                            "%s 読み取り専用リクエストプロパティのmaxが %s に減少しました",
	"ja.messages.request-read-only-property-max-decreased-description":                "読み取り専用リクエストプロパティのmaxが減少しました",
	"ja.messages.request-read-only-property-max-length-decreased":                     "%s 読み取り専用リクエストプロパティのmaxLengthが %s に減少しました",
	"ja.messages.request-read-only-property-max-length-decreased-description":         "読み取り専用リクエストプロパティのmaxLengthが減少しました",
	"ja.messages.request-read-only-property-min-increased":                            "%s 読み取り専用リクエストプロパティのminが %s に増加しました",
	"ja.messages.request-read-only-property-min-increased-description":                "読み取り専用リクエストプロパティのminが増加しました",
	"ja.messages.request-required-property-became-not-read-only":                      "必須リクエストプロパティ %s が読み取り専用でなくなりました",
	"ja.messages.request-required-property-became-not-read-only-description":          "必須リクエストプロパティが読み取り専用でなくなりました",
	"ja.messages.request-required-property-became-not-write-only":                     "必須リクエストプロパティ %s が書き込み専用でなくなりました",
	"ja.messages.request-required-property-became-not-write-only-description":         "必須リクエストプロパティが書き込み専用でなくなりました",
	"ja.messages.request-required-property-became-read-only":                          "必須リクエストプロパティ %s が読み取り専用になりました",
	"ja.messages.request-required-property-became-read-only-description":              "必須リクエストプロパティが読み取り専用になりました",
	"ja.messages.request-required-property-became-write-only":                         "必須リクエストプロパティ %s が書き込み専用になりました",
	"ja.messages.request-required-property-became-write-only-description":             "必須リクエストプロパティが書き込み専用になりました",
	"ja.messages.required-response-header-removed":                                    "必須レスポンスヘッダー %s がステータス %s から削除されました",
	"ja.messages.required-response-header-removed-description":                        "必須レスポンスヘッダーが削除されました",
	"ja.messages.response-body-all-of-added":                                          "レスポンスステータス %s のレスポンスボディ 'allOf' リストに %s が追加されました",
	"ja.messages.response-body-all-of-added-description":                              "レスポンスボディのallOfにサブスキーマが追加されました",
	"ja.messages.response-body-all-of-removed":                                        "レスポンスステータス %s のレスポンスボディ 'allOf' リストから %s が削除されました",
	"ja.messages.response-body-all-of-removed-description":                            "レスポンスボディのallOfからサブスキーマが削除されました",
	"ja.messages.response-body-any-of-added":                                          "レスポンスステータス %s のレスポンスボディ 'anyOf' リストに %s が追加されました",
	"ja.messages.response-body-any-of-added-description":                              "レスポンスボディのanyOfにサブスキーマが追加されました",
	"ja.messages.response-body-any-of-removed":                                        "レスポンスステータス %s のレスポンスボディ 'anyOf' リストから %s が削除されました",
	"ja.messages.response-body-any-of-removed-description":                            "レスポンスボディのanyOfからサブスキーマが削除されました",
	"ja.messages.response-body-became-nullable":                                       "レスポンスボディがnull許容になりました",
	"ja.messages.response-body-became-nullable-description":                           "レスポンスボディがnull許容になりました",
	"ja.messages.response-body-default-value-added":                                   "ステータス %s のレスポンスボディ %s にデフォルト値 %s が追加されました",
	"ja.messages.response-body-default-value-added-description":                       "レスポンスボディのデフォルト値が設定されました",
	"ja.messages.response-body-default-value-changed":                                 "ステータス %s のレスポンスボディ %s のデフォルト値が %s から %s に変更されました",
	"ja.messages.response-body-default-value-changed-description":                     "レスポンスボディのデフォルト値が変更されました",
	"ja.messages.response-body-default-value-removed":                                 "ステータス %s のレスポンスボディ %s のデフォルト値 %s が削除されました",
	"ja.messages.response-body-default-value-removed-description":                     "レスポンスボディのデフォルト値が解除されました",
	"ja.messages.response-body-discriminator-added":                                   "レスポンスステータス %s のレスポンスにdiscriminatorが追加されました",
	"ja.messages.response-body-discriminator-added-description":                       "レスポンスボディにdiscriminatorが追加されました",
	"ja.messages.response-body-discriminator-mapping-added":                           "レスポンスステータス %s のレスポンスdiscriminatorにマッピングキー %s が追加されました",
	"ja.messages.response-body-discriminator-mapping-added-description":               "レスポンスボディにdiscriminatorマッピングが追加されました",
	"ja.messages.response-body-discriminator-mapping-changed":                         "レスポンスステータス %s のレスポンスdiscriminatorのキー %s にマップされた値が %s から %s に変更されました",
	"ja.messages.response-body-discriminator-mapping-changed-description":             "レスポンスボディのdiscriminatorマッピングが変更されました",
	"ja.messages.response-body-discriminator-mapping-deleted":                         "レスポンスステータス %s のレスポンスdiscriminatorからマッピングキー %s が削除されました",
	"ja.messages.response-body-discriminator-mapping-deleted-description":             "レスポンスボディのdiscriminatorマッピングが削除されました",
	"ja.messages.response-body-discriminator-property-name-changed":                   "レスポンスステータス %s のレスポンスdiscriminatorプロパティ名が %s から %s に変更されました",
	"ja.messages.response-body-discriminator-property-name-changed-description":       "レスポンスボディのdiscriminatorプロパティ名が変更されました",
	"ja.messages.response-body-discriminator-removed":                                 "レスポンスステータス %s のレスポンスからdiscriminatorが削除されました",
	"ja.messages.response-body-discriminator-removed-description":                     "レスポンスボディのdiscriminatorが削除されました",
	"ja.messages.response-body-max-increased":                                         "レスポンスボディのmaxが %s から %s に増加しました",
	"ja.messages.response-body-max-increased-description":                             "レスポンスボディのmaxが増加しました",
	"ja.messages.response-body-max-length-increased":                                  "レスポンスボディのmaxLengthが %s から %s に増加しました",
	"ja.messages.response-body-max-length-increased-description":                      "レスポンスボディのmaxLengthが増加しました",
	"ja.messages.response-body-max-length-unset":                                      "レスポンスボディのmaxLength（以前の値: %s）が解除されました",
	"ja.messages.response-body-max-length-unset-description":                          "レスポンスボディのmaxLengthが解除されました",
	"ja.messages.response-body-min-decreased":                                         "レスポンスボディのminが %s から %s に減少しました",
	"ja.messages.response-body-min-decreased-description":                             "レスポンスボディのminが減少しました",
	"ja.messages.response-body-min-items-decreased":                                   "レスポンスボディのminItemsが %s から %s に減少しました",
	"ja.messages.response-body-min-items-decreased-description":                       "レスポンスボディのminItemsが減少しました",
	"ja.messages.response-body-min-items-unset":                                       "レスポンスボディのminItems（以前の値: %s）が解除されました",
	"ja.messages.response-body-min-items-unset-description":                           "レスポンスボディのminItemsが解除されました",
	"ja.messages.response-body-min-length-decreased":                                  "レスポンスボディのminLengthが %s から %s に減少しました",
	"ja.messages.response-body-min-length-decreased-description":                      "レスポンスボディのminLengthが減少しました",
	"ja.messages.response-body-one-of-added":                                          "レスポンスステータス %s のレスポンスボディ 'oneOf' リストに %s が追加されました",
	"ja.messages.response-body-one-of-added-description":                              "レスポンスボディのoneOfにサブスキーマが追加されました",
	"ja.messages.response-body-one-of-removed":                                        "レスポンスステータス %s のレスポンスボディ 'oneOf' リストから %s が削除されました",
	"ja.messages.response-body-one-of-removed-description":                            "レスポンスボディのoneOfからサブスキーマが削除されました",
	"ja.messages.response-body-type-changed":                                          "ステータス %s のレスポンスボディのtype/formatが %s/%s から %s/%s に変更されました",
	"ja.messages.response-body-type-changed-description":                              "レスポンスボディのタイプが変更されました",
	"ja.messages.response-header-became-optional":                                     "ステータス %s のレスポンスヘッダー %s がオプションになりました",
	"ja.messages.response-header-became-optional-description":                         "レスポンスヘッダーがオプションになりました",
	"ja.messages.response-media-type-added":                                           "ステータス %s のレスポンスにメディアタイプ %s が追加されました",
	"ja.messages.response-media-type-added-description":                               "レスポンスのメディアタイプが追加されました",
	"ja.messages.response-media-type-name-changed":                                    "レスポンスステータス %s のメディアタイプが %s から %s に変更されました",
	"ja.messages.response-media-type-name-generalized":                                "レスポンスステータス %s のメディアタイプ %s が、より汎用的な %s に変更されました",
	"ja.messages.response-media-type-name-specialized":                                "レスポンスステータス %s のメディアタイプ %s が、より具体的な %s に変更されました",
	"ja.messages.response-media-type-removed":                                         "ステータス %s のレスポンスからメディアタイプ %s が削除されました",
	"ja.messages.response-media-type-removed-description":                             "レスポンスのメディアタイプが削除されました",
	"ja.messages.response-mediatype-enum-value-removed":                               "レスポンススキーマ %s からenum値 %s が削除されました",
	"ja.messages.response-mediatype-enum-value-removed-description":                   "レスポンスメディアタイプのenum値が削除されました",
	"ja.messages.response-non-success-status-added":                                   "ステータス %s の非成功レスポンスが追加されました",
	"ja.messages.response-non-success-status-added-description":                       "非成功レスポンスステータスが追加されました",
	"ja.messages.response-non-success-status-removed":                                 "ステータス %s の非成功レスポンスが削除されました",
	"ja.messages.response-non-success-status-removed-description":                     "非成功レスポンスステータスが削除されました",
	"ja.messages.response-optional-property-added":                                    "ステータス %s のレスポンスにオプションのプロパティ %s が追加されました",
	"ja.messages.response-optional-property-added-description":                        "レスポンスにオプションのプロパティが追加されました",
	"ja.messages.response-optional-property-became-not-read-only":                     "ステータス %s のレスポンスのオプションプロパティ %s が読み取り専用でなくなりました",
	"ja.messages.response-optional-property-became-not-read-only-description":         "レスポンスのオプションプロパティが読み取り専用でなくなりました",
	"ja.messages.response-optional-property-became-not-write-only":                    "ステータス %s のレスポンスのオプションプロパティ %s が書き込み専用でなくなりました",
	"ja.messages.response-optional-property-became-not-write-only-description":        "レスポンスのオプションプロパティが書き込み専用でなくなりました",
	"ja.messages.response-optional-property-became-read-only":                         "ステータス %s のレスポンスのオプションプロパティ %s が読み取り専用になりました",
	"ja.messages.response-optional-property-became-read-only-description":             "レスポンスのオプションプロパティが読み取り専用になりました",
	"ja.messages.response-optional-property-became-write-only":                        "ステータス %s のレスポンスのオプションプロパティ %s が書き込み専用になりました",
	"ja.messages.response-optional-property-became-write-only-description":            "レスポンスのオプションプロパティが書き込み専用になりました",
	"ja.messages.response-optional-property-removed":                                  "ステータス %s のレスポンスからオプションのプロパティ %s が削除されました",
	"ja.messages.response-optional-property-removed-description":                      "レスポンスのオプションプロパティが削除されました",
	"ja.messages.response-optional-write-only-property-added":                         "ステータス %s のレスポンスにオプションの書き込み専用プロパティ %s が追加されました",
	"ja.messages.response-optional-write-only-property-added-description":             "レスポンスにオプションの書き込み専用プロパティが追加されました",
	"ja.messages.response-optional-write-only-property-removed":                       "ステータス %s のレスポンスからオプションの書き込み専用プロパティ %s が削除されました",
	"ja.messages.response-optional-write-only-property-removed-description":           "レスポンスのオプションの書き込み専用プロパティが削除されました",
	"ja.messages.response-property-all-of-added":                                      "レスポンスステータス %s のレスポンスプロパティ %s の 'allOf' リストに %s が追加されました",
	"ja.messages.response-property-all-of-added-description":                          "レスポンスプロパティのallOfにサブスキーマが追加されました",
	"ja.messages.response-property-all-of-removed":                                    "レスポンスステータス %s のレスポンスプロパティ %s の 'allOf' リストから %s が削除されました",
	"ja.messages.response-property-all-of-removed-description":                        "レスポンスプロパティのallOfからサブスキーマが削除されました",
	"ja.messages.response-property-any-of-added":                                      "レスポンスステータス %s のレスポンスプロパティ %s の 'anyOf' リストに %s が追加されました",
	"ja.messages.response-property-any-of-added-description":                          "レスポンスプロパティのanyOfにサブスキーマが追加されました",
	"ja.messages.response-property-any-of-removed":                                    "レスポンスステータス %s のレスポンスプロパティ %s の 'anyOf' リストから %s が削除されました",
	"ja.messages.response-property-any-of-removed-description":                        "レスポンスプロパティのanyOfからサブスキーマが削除されました",
	"ja.messages.response-property-became-nullable":                                   "ステータス %s のレスポンスプロパティ %s がnull許容になりました",
	"ja.messages.response-property-became-nullable-description":                       "レスポンスプロパティがnull許容になりました",
	"ja.messages.response-property-became-optional":                                   "ステータス %s のレスポンスプロパティ %s がオプションになりました",
	"ja.messages.response-property-became-optional-description":                       "レスポンスプロパティがオプションになりました",
	"ja.messages.response-property-became-required":                                   "ステータス %s のレスポンスプロパティ %s が必須になりました",
	"ja.messages.response-property-became-required-description":                       "レスポンスプロパティが必須になりました",
	"ja.messages.response-property-default-value-added":                               "ステータス %s の %s レスポンスプロパティにデフォルト値 %s が追加されました",
	"ja.messages.response-property-default-value-added-description":                   "レスポンスプロパティのデフォルト値が設定されました",
	"ja.messages.response-property-default-value-changed":                             "ステータス %s の %s レスポンスプロパティのデフォルト値が %s から %s に変更されました",
	"ja.messages.response-property-default-value-changed-description":                 "レスポンスプロパティのデフォルト値が変更されました",
	"ja.messages.response-property-default-value-removed":                             "ステータス %s の %s レスポンスプロパティのデフォルト値 %s が削除されました",
	"ja.messages.response-property-default-value-removed-description":                 "レスポンスプロパティのデフォルト値が解除されました",
	"ja.messages.response-property-discriminator-added":                               "レスポンスステータス %s の %s レスポンスプロパティにdiscriminatorが追加されました",
	"ja.messages.response-property-discriminator-added-description":                   "レスポンスプロパティにdiscriminatorが追加されました",
	"ja.messages.response-property-discriminator-mapping-added":                       "レスポンスステータス %s の %s レスポンスプロパティにdiscriminatorマッピングキー %s が追加されました",
	"ja.messages.response-property-discriminator-mapping-added-description":           "レスポンスプロパティにdiscriminatorマッピングが追加されました",
	"ja.messages.response-property-discriminator-mapping-changed":                     "レスポンスステータス %s の %s レスポンスプロパティのdiscriminatorキー %s にマップされた値が %s から %s に変更されました",
	"ja.messages.response-property-discriminator-mapping-changed-description":         "レスポンスプロパティのdiscriminatorマッピングが変更されました",
	"ja.messages.response-property-discriminator-mapping-deleted":                     "レスポンスステータス %s の %s レスポンスプロパティからdiscriminatorマッピングキー %s が削除されました",
	"ja.messages.response-property-discriminator-mapping-deleted-description":         "レスポンスプロパティのdiscriminatorマッピングが削除されました",
	"ja.messages.response-property-discriminator-property-name-changed":               "レスポンスステータス %s の %s レスポンスプロパティのdiscriminatorプロパティ名が %s から %s に変更されました",
	"ja.messages.response-property-discriminator-property-name-changed-description":   "レスポンスプロパティのdiscriminatorプロパティ名が変更されました",
	"ja.messages.response-property-discriminator-removed":                             "レスポンスステータス %s の %s レスポンスプロパティからdiscriminatorが削除されました",
	"ja.messages.response-property-discriminator-removed-description":                 "レスポンスプロパティのdiscriminatorが削除されました",
	"ja.messages.response-property-enum-value-added":                                  "新しいenum値 %s がステータス %s の %s レスポンスプロパティに追加されました",
	"ja.messages.response-property-enum-value-added-comment":                          "レスポンスに新しいenum値を追加するとクライアントが予期しない動作をする可能性があります。代わりにx-extensible-enumを使用してください。",
	"ja.messages.response-property-enum-value-added-description":                      "レスポンスプロパティにenum値が追加されました",
	"ja.messages.response-property-enum-value-removed":                                "enum値 %s がステータス %s の %s レスポンスプロパティから削除されました",
	"ja.messages.response-property-enum-value-removed-description":                    "レスポンスプロパティのenum値が削除されました",
	"ja.messages.response-property-max-increased":                                     "レスポンスステータス %s の %s レスポンスプロパティのmaxが %s から %s に増加しました",
	"ja.messages.response-property-max-increased-description":                         "レスポンスプロパティのmaxが増加しました",
	"ja.messages.response-property-max-length-increased":                              "レスポンスステータス %s の %s レスポンスプロパティのmaxLengthが %s から %s に増加しました",
	"ja.messages.response-property-max-length-increased-description":                  "レスポンスプロパティのmaxLengthが増加しました",
	"ja.messages.response-property-max-length-unset":                                  "レスポンスステータス %s の %s レスポンスプロパティのmaxLength（以前の値: %s）が解除されました",
	"ja.messages.response-property-max-length-unset-description":                      "レスポンスプロパティのmaxLengthが解除されました",
	"ja.messages.response-property-min-decreased":                                     "レスポンスステータス %s の %s レスポンスプロパティのminが %s から %s に減少しました",
	"ja.messages.response-property-min-decreased-description":                         "レスポンスプロパティのminが減少しました",
	"ja.messages.response-property-min-items-decreased":                               "レスポンスステータス %s の %s レスポンスプロパティのminItemsが %s から %s に減少しました",
	"ja.messages.response-property-min-items-decreased-description":                   "レスポンスプロパティのminItemsが減少しました",
	"ja.messages.response-property-min-items-unset":                                   "レスポンスステータス %s の %s レスポンスプロパティのminItems（以前の値: %s）が解除されました",
	"ja.messages.response-property-min-items-unset-description":                       "レスポンスプロパティのminItemsが解除されました",
	"ja.messages.response-property-min-length-decreased":                              "レスポンスステータス %s の %s レスポンスプロパティのminLengthが %s から %s に減少しました",
	"ja.messages.response-property-min-length-decreased-description":                  "レスポンスプロパティのminLengthが減少しました",
	"ja.messages.response-property-one-of-added":                                      "レスポンスステータス %s の %s レスポンスプロパティの 'oneOf' リストに %s が追加されました",
	"ja.messages.response-property-one-of-added-description":                          "レスポンスプロパティのoneOfにサブスキーマが追加されました",
	"ja.messages.response-property-one-of-removed":                                    "レスポンスステータス %s の %s レスポンスプロパティの 'oneOf' リストから %s が削除されました",
	"ja.messages.response-property-one-of-removed-description":                        "レスポンスプロパティのoneOfからサブスキーマが削除されました",
	"ja.messages.response-property-pattern-added":                                     "ステータス %s の %s レスポンスプロパティにパターン %s が追加されました",
	"ja.messages.response-property-pattern-added-description":                         "レスポンスプロパティのパターンが設定されました",
	"ja.messages.response-property-pattern-changed":                                   "ステータス %s の %s レスポンスプロパティのパターンが %s から %s に変更されました",
	"ja.messages.response-property-pattern-changed-description":                       "レスポンスプロパティのパターンが変更されました",
	"ja.messages.response-property-pattern-removed":                                   "ステータス %s の %s レスポンスプロパティのパターン %s が削除されました",
	"ja.messages.response-property-pattern-removed-description":                       "レスポンスプロパティのパターンが解除されました",
	"ja.messages.response-property-type-changed":                                      "ステータス %s の %s レスポンスプロパティのtype/formatが %s/%s から %s/%s に変更されました",
	"ja.messages.response-property-type-changed-description":                          "レスポンスプロパティのタイプが変更されました",
	"ja.messages.response-required-property-added":                                    "ステータス %s のレスポンスに必須プロパティ %s が追加されました",
	"ja.messages.response-required-property-added-description":                        "レスポンスに必須プロパティが追加されました",
	"ja.messages.response-required-property-became-not-read-only":                     "ステータス %s のレスポンスの必須プロパティ %s が読み取り専用でなくなりました",
	"ja.messages.response-required-property-became-not-read-only-description":         "レスポンスの必須プロパティが読み取り専用でなくなりました",
	"ja.messages.response-required-property-became-not-write-only":                    "ステータス %s のレスポンスの必須プロパティ %s が書き込み専用でなくなりました",
	"ja.messages.response-required-property-became-not-write-only-comment":            "この変更が有効なのは、仕様変更前からプロパティが常に返されていた場合のみです",
	"ja.messages.response-required-property-became-not-write-only-description":        "レスポンスの必須プロパティが書き込み専用でなくなりました",
	"ja.messages.response-required-property-became-read-only":                         "ステータス %s のレスポンスの必須プロパティ %s が読み取り専用になりました",
	"ja.messages.response-required-property-became-read-only-description":             "レスポンスの必須プロパティが読み取り専用になりました",
	"ja.messages.response-required-property-became-write-only":                        "ステータス %s のレスポンスの必須プロパティ %s が書き込み専用になりました",
	"ja.messages.response-required-property-became-write-only-description":            "レスポンスの必須プロパティが書き込み専用になりました",
	"ja.messages.response-required-property-removed":                                  "ステータス %s のレスポンスから必須プロパティ %s が削除されました",
	"ja.messages.response-required-property-removed-description":                      "レスポンスの必須プロパティが削除されました",
	"ja.messages.response-required-write-only-property-added":                         "ステータス %s のレスポンスに必須の書き込み専用プロパティ %s が追加されました",
	"ja.messages.response-required-write-only-property-added-description":             "レスポンスに必須の書き込み専用プロパティが追加されました",
	"ja.messages.response-required-write-only-property-removed":                       "ステータス %s のレスポンスから必須の書き込み専用プロパティ %s が削除されました",
	"ja.messages.response-required-write-only-property-removed-description":           "レスポンスの必須の書き込み専用プロパティが削除されました",
	"ja.messages.response-success-status-added":                                       "ステータス %s の成功レスポンスが追加されました",
	"ja.messages.response-success-status-added-description":                           "成功レスポンスステータスが追加されました",
	"ja.messages.response-success-status-removed":                                     "ステータス %s の成功レスポンスが削除されました",
	"ja.messages.response-success-status-removed-description":                         "成功レスポンスステータスが削除されました",
	"ja.messages.response-write-only-property-became-optional":                        "ステータス %s のレスポンスの書き込み専用プロパティ %s がオプションになりました",
	"ja.messages.response-write-only-property-became-optional-description":            "レスポンスの書き込み専用プロパティがオプションになりました",
	"ja.messages.response-write-only-property-became-required":                        "ステータス %s のレスポンスの書き込み専用プロパティ %s が必須になりました",
	"ja.messages.response-write-only-property-became-required-description":            "レスポンスの書き込み専用プロパティが必須になりました",
	"ja.messages.response-write-only-property-enum-value-added":                       "新しいenum値 %s がレスポンスステータス %s の %s 書き込み専用レスポンスプロパティに追加されました",
	"ja.messages.response-write-only-property-enum-value-added-description":           "レスポンスの書き込み専用プロパティにenum値が追加されました",
	"ja.messages.sunset-deleted":                                                      "APIの廃止日が削除されましたが、deprecated=trueは維持されます",
	"ja.messages.sunset-deleted-description":                                          "廃止日が削除されました",
	"ja.messages.total-changes":                                                       "合計%d件の変更: %sが%d件, %sが%d件, %sが%d件\n",
	"ja.messages.total-errors":                                                        "合計%d件の互換性を損なう変更: %sが%d件, %sが%d件\n",
}
