import { Inter } from "next/font/google";
import "./globals.css";
import type React from "react";
import { AppShell } from "@/components/app-shell";
import { getApiData } from "@/lib/api-loader"; // ★ インポート
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "API Document Viewer",
  description: "Generated by the custom static site generator.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { apis } = getApiData();

  return (
    <html lang="ja" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.className,
        )}
      >
        <AppShell apis={apis}>{children}</AppShell>
      </body>
    </html>
  );
}
